version: '3.1'

services: 
  php:
    container_name: apache_server
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 80:80
    volumes: 
      - ./src:/var/www/html
  
  db:
    container_name: mysql_server
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: loginTutorial
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes: 
      - ${PWD}/mysql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080