#!/bin/bash
docker run -dit --name php_apache -p 8082:80 -v "$PWD/htdocs":/var/www/html php:apache


docker run -d --name mariadb-server -p 3306:3306 -v "$PWD/mysql":/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mypass mariadb
docker exec -it mariadb-server mysql -uroot -pmypass
# CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';
# GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';
